apiVersion: v2
name: external-secrets
description: external-secrets
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: external-secrets
    version: 0.8.1
    repository: https://charts.external-secrets.io/